repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==23.11.0]
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==3.15.0]
      - id: nbqa-isort
        args: [--profile=black]
        additional_dependencies: [isort==5.12.0]
